/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 14.05.2026 10:55:00

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1568;
#else
constexpr int kTensorArenaSize = 544;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,208 } };
const TfArray<1, float> quant0_scale = { 1, { 73.789535522460938, } };
const TfArray<1, int> quant0_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 0, 0, 1, 0, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const TfArray<1, float> quant1_scale = { 1, { 0.057478521019220352, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[4*10] = { 
  71, 70, 121, -47, 8, -105, -127, -27, 120, 56, 
  71, -23, -92, -110, -93, -95, 16, 35, -40, 18, 
  -99, 109, -80, -105, 95, -99, 117, 67, 68, -72, 
  17, -23, 3, 54, 34, -53, 92, -33, -99, -115, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 4,10 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0051584481261670589, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[10] = { -1, 0, -1, 0, 1, 0, 1, 1, 0, -1, };
const TfArray<1, int> tensor_dimension3 = { 1, { 10 } };
const TfArray<1, float> quant3_scale = { 1, { 0.040915101766586304, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[10*20] = { 
  47, -81, -88, 13, 108, 17, 116, -116, -6, -55, 22, 17, 65, 124, 59, -90, -4, -38, -77, 27, 
  -61, -121, 78, 76, 62, -44, -53, -102, -101, 20, -53, -54, 68, 24, 76, 97, -52, 41, -48, -33, 
  -21, -107, -8, 110, -58, -64, -41, 18, -45, -12, 32, 49, -27, -94, -14, -76, 91, -110, -109, -88, 
  63, 10, 96, 3, -72, 83, -66, -40, -30, 80, 108, 51, -76, -102, -5, -49, -25, -67, 115, 91, 
  -49, 60, -92, -48, -99, 76, -32, 26, -100, 67, 99, 60, -18, 54, 27, -103, -39, 112, 79, 63, 
  -98, 78, -78, 59, -28, -127, -6, 92, -126, -51, 86, 70, -51, 68, -26, -74, -38, 67, -74, 4, 
  96, 50, -56, -82, 91, 85, 16, -32, -29, 3, 71, 49, -74, -45, 10, -19, 67, -14, -18, -38, 
  -21, 98, 59, 69, -10, 94, 99, -122, 124, -33, -60, 127, 68, -29, -109, 54, 92, 13, 15, 91, 
  70, 37, 58, 38, 88, 36, -124, -35, -32, 13, 97, 17, -9, -114, -37, 104, -98, 72, -52, -35, 
  49, -83, -24, -8, 81, 110, -28, 6, 84, -101, -71, 47, -85, -59, 61, -20, -27, 91, 3, 84, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 10,20 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0035227341577410698, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[20] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, };
const TfArray<1, int> tensor_dimension5 = { 1, { 20 } };
const TfArray<1, float> quant5_scale = { 1, { 0.20550288259983063, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[20*208] = { 
  -10, -7, -23, 37, 14, 17, 5, -48, 8, -57, -13, 9, -62, -49, -3, 40, 4, 43, -39, -39, 38, -26, 36, -1, -64, 25, -39, -23, -49, -59, 4, 6, 23, -59, -65, 13, -47, 30, -17, -48, 14, -16, -54, -25, -61, 36, -32, 39, -49, -52, -22, -65, 11, -20, -59, 26, 47, 31, 45, 22, 10, -34, -5, -52, -20, -51, 6, 7, 37, -12, 2, -60, -47, -27, -23, -43, 28, 15, -18, 35, 5, -13, -19, 6, -23, -4, -69, -18, -55, -65, 9, -18, -31, 37, -18, -64, 44, 20, -54, -33, -15, -68, 1, 19, -20, -27, -32, -9, -41, -38, 35, 6, -8, 26, -39, 42, -36, 14, -64, 8, 15, -8, 2, 42, -68, -21, 25, -8, 35, -19, -61, -39, 64, 4, 34, -42, -9, 44, -25, -10, 16, -13, -50, -47, -32, -18, -25, 16, -45, -41, -36, 22, -26, 21, 6, -33, 32, 0, -51, -13, 10, 32, -44, -35, -32, -36, -53, -53, 24, 35, -43, -1, -27, -30, -21, 31, 20, 18, -49, -53, -5, 8, -62, -29, 5, 9, -39, -66, 21, -12, 41, -50, -3, 45, 18, 12, -47, 54, -63, -15, -30, 23, 40, 6, 6, -48, 27, -42, 
  -40, 29, 32, 23, 1, 24, 33, 32, 40, 68, -22, 40, 24, 31, 32, -47, 68, 61, 74, -20, 4, 8, 60, 3, 43, 42, 8, 66, -17, -32, -8, 70, 67, 73, 57, 0, -26, 13, 34, -5, -65, -11, 63, 34, 47, 0, 58, -25, 20, 17, -36, 11, 9, -48, -14, -44, -37, 57, 59, -35, 1, 51, -12, 2, -2, 5, 23, -53, 46, -21, 65, -20, 47, 10, 21, 59, -5, -19, 3, 62, 31, -50, -32, 12, 40, 18, 1, -28, 25, -1, 32, 44, 42, 32, 18, 48, -11, -31, 26, -33, 30, 72, 17, 8, -16, 4, 62, -20, 10, 5, -2, -35, 73, 34, -1, 66, 29, 35, -61, -22, 28, -40, -3, -15, 42, 12, 16, 38, -31, 69, -20, -59, 51, -2, 74, 47, -24, -5, 3, 48, -42, 20, 6, -20, -11, 22, 48, 38, -9, -20, -13, -7, -13, -8, -9, 54, 36, 107, 8, -9, -9, -35, 43, -14, -35, -6, -31, 22, -38, -10, 7, -33, 40, 1, 3, 50, 43, -6, -19, -22, -32, 26, 24, 12, -35, 63, 22, 1, 48, 68, 57, 35, 54, 62, 4, 15, -51, -53, -33, 71, 53, -9, -36, 17, -21, 17, 43, 62, 
  38, -11, -47, -42, 22, -31, 34, 48, 54, -6, -44, 9, -43, 28, -38, 40, 17, 32, 0, 24, 56, -54, 31, -46, 6, -16, 52, 27, -29, -46, -29, 37, 28, -43, -12, -20, -51, -5, 32, -46, 25, 36, -55, -12, 19, -12, -31, -47, 20, -16, 29, -14, -12, -15, 23, -46, 11, 7, 5, -17, 52, -21, -10, 8, -17, 31, 8, -31, -20, -18, -4, -57, 3, 47, -11, -50, -50, 30, -28, -40, 20, -33, 17, -3, 4, 9, -15, -2, -46, -1, -41, 51, 4, -29, 58, 42, 18, 28, 19, 16, -56, -50, -30, -42, 29, -33, 42, 41, 6, -10, -28, 29, 4, -46, -36, -48, 26, 61, -24, 14, -29, 49, 57, -56, 50, 48, 15, 38, -49, -4, 28, -37, 20, 29, 32, 26, -30, 41, 32, 18, -10, 49, 51, 47, -48, 1, -49, 5, -22, 6, 23, -31, -21, 4, 21, 54, 28, -22, 58, -43, 4, 39, 11, 50, -4, -36, -26, -11, -22, -12, -43, -15, 2, -55, -20, 9, 33, -29, -30, -52, 33, -47, -7, 65, -46, 7, 29, -11, 24, -39, 4, 14, -21, 45, -1, -46, 8, -44, -43, -3, 51, -4, 8, -18, -50, -47, 14, 4, 
  -60, -1, -15, 22, -18, 23, -17, 44, 17, -61, 35, 33, 15, 19, 19, 3, -64, -59, 7, 26, -48, 13, -47, -32, 24, 19, -59, 13, 50, 30, -22, 10, 34, -40, 20, -8, 40, -70, -5, 22, -12, 28, -5, 47, 44, -56, -14, -49, 22, 13, -51, -15, -18, -33, 24, -53, -58, -66, -32, -16, 43, 10, 45, 31, -48, -58, 41, -46, -49, -47, 23, -40, -41, -52, 2, 10, -24, 47, 19, 45, -25, 32, 42, -27, -21, -56, -14, -31, 25, -32, 13, 2, -43, -13, 38, -29, -46, -23, 33, -27, -32, -18, 33, -46, -43, 11, -15, -27, -4, 6, -59, -2, -14, 30, -7, 40, -62, -13, 51, -25, -62, 41, -9, 7, -59, -10, -13, -47, 2, 7, -23, -8, -27, 40, -22, -38, -48, 2, -5, 29, 25, 29, 5, -29, 25, 29, -32, -45, -30, -54, -26, -47, 36, 41, -47, 9, 19, 9, -80, -62, -40, 16, 38, 25, -40, 6, -29, -50, 11, 5, -70, -33, -13, -67, 24, 16, 10, 16, 32, -67, -23, 32, 43, 65, 11, -71, -30, 27, -6, -43, -18, -55, -7, -44, -8, 49, -16, -38, -49, -44, -37, -22, -45, -33, -6, -13, -6, 29, 
  36, 6, -31, -51, -55, -61, 30, -31, -45, 17, -34, -6, -53, -44, 4, 13, 26, 58, -25, -33, -25, 34, -29, -28, -37, -15, 30, 56, -60, -66, 5, -54, 36, -57, -34, -44, -31, -67, -4, 8, 10, -19, -65, -24, 12, -56, 23, 16, -30, 20, 18, 23, -50, -17, -42, 25, -3, 29, 35, 20, -64, -60, 38, 39, -10, 20, 5, 21, -77, -43, -70, -5, 20, 4, 5, 7, -39, -32, -52, -22, 51, -76, 6, -62, 1, -51, -5, -60, 20, -40, -39, -22, 21, 42, -13, -38, -6, -27, -55, -56, -25, -64, 1, -28, 32, -34, -40, -35, -58, 5, -47, -11, -41, -11, 12, -12, -31, -59, -31, 3, 24, -52, -47, -19, -60, -6, 43, -55, -36, 14, -38, -20, 7, -34, -46, -31, 11, 11, -71, 23, -1, -9, 18, 3, 3, -74, 21, -19, -64, -66, -23, 11, -36, -55, 11, 43, 37, -31, 48, -62, -42, 20, -69, -30, -73, -56, -7, -38, 35, -29, -32, -32, -63, 15, 14, -10, -40, 13, -36, 0, -42, -13, 9, -30, 43, -63, -44, -55, 27, -55, 30, -40, 4, -53, -41, 33, 26, 5, -13, -42, -57, 36, -10, -69, -58, -68, -29, -25, 
  -17, 43, 10, -2, -19, -46, 6, 57, -22, 13, -54, -21, -57, 27, 10, -1, -52, 16, -18, 5, -45, -48, -6, -29, 42, -15, 16, -8, -27, 57, -11, -6, 45, -35, 13, -54, 39, -33, 24, 50, 39, 22, -40, -16, 10, -57, -43, -38, -2, 37, 51, -8, 19, -23, 25, 34, 19, -7, 32, 4, 15, -55, 38, -45, -16, 0, -21, 46, 50, 26, 54, -26, 39, -42, -57, -37, -7, -9, 37, 0, -45, 21, -29, 45, -5, -44, 17, -4, 57, -10, 7, 4, -35, 44, 2, -5, -7, 19, -1, 35, -8, 17, 46, -33, 13, 9, 56, -38, 20, 32, -6, -5, 17, 33, 40, 11, 28, -45, 16, -36, -57, 32, -44, 8, 2, 53, -9, -22, -28, -52, 4, 19, -37, -20, 11, 50, 25, -44, 44, 53, 32, -1, 0, -32, 9, -32, 51, 53, 50, -27, 44, 15, 20, -52, 40, -4, -18, 44, -23, -3, 33, -57, 29, -47, 38, -56, 55, -32, 32, 5, -3, 48, -49, 1, -48, 16, -45, -16, 56, 28, 48, 19, -56, -44, -8, -32, 2, -29, 57, -49, -30, 57, 29, 7, 14, -38, 52, -3, 41, 3, -6, 21, 39, 36, -52, -44, -44, -19, 
  35, -13, -33, -30, -33, -54, -17, 43, -18, 7, 0, -2, 3, 29, 45, -13, -21, -22, 56, 45, -26, 12, -24, 39, -22, -4, 62, -51, 43, 18, 41, -51, 3, -5, -43, 35, -50, 26, -45, 57, -7, -7, 2, 18, -27, -48, 57, -30, -4, -12, -37, 48, -43, 53, 15, -8, -3, 50, 35, -17, -33, 9, 44, -32, 31, 22, -45, 31, -41, -23, 10, 52, -16, 29, 18, 36, 28, 49, 27, -20, 42, 37, 6, 19, -31, -14, 39, 18, -24, -22, -38, 31, -3, 54, -21, -63, -23, -29, -45, 0, -29, -28, 8, -10, 54, 14, -8, -40, -34, 2, 4, 37, 45, -51, 20, -6, 39, -24, -29, -16, -33, 6, -42, 7, -14, -39, 1, 32, -9, -40, 27, -45, -27, 25, 28, 48, -45, 27, 42, 59, 24, 36, -21, -47, -45, -9, 40, -52, 48, 40, -37, 51, -1, 52, -20, -49, 17, -36, 8, -27, 57, 22, -9, -38, 38, -22, -21, 34, 43, 15, -66, 44, 38, 60, 28, -46, -54, -22, 23, -11, 42, -18, 58, -24, 4, -52, 29, -45, -41, -50, 35, -32, 41, -13, -46, -8, 61, 52, -8, 5, -32, -29, -13, -28, -3, 55, 61, 7, 
  35, -38, 36, 50, 50, 16, 16, 23, -18, 49, -12, 56, -20, 27, -59, -61, -24, -46, -37, 55, 48, -35, -31, 0, -12, 55, -17, 34, -59, -8, 13, 53, 12, -51, -21, -53, -10, 15, 42, -7, -8, 21, 57, 53, 22, -4, 13, -47, -33, 31, -37, -13, -14, 11, -10, -32, -42, 40, 37, -58, -39, -20, 29, -42, 30, 9, 28, -16, -28, 48, -34, 11, -11, 18, 0, 11, -21, 27, -34, 6, 58, -55, 39, -3, 13, -57, 21, 23, 37, -23, -18, -57, -5, -28, -42, -11, -27, -59, -7, 44, -27, 27, -11, -61, -16, -31, -34, -47, 64, -32, -47, -59, -4, 14, 37, -38, 31, -20, -31, 21, -14, 27, -17, -61, 10, 9, -50, -60, -25, -23, 36, -22, 9, 13, -25, 35, -11, -12, 4, -5, -8, 33, 33, 36, 8, 42, -2, -41, 37, 10, 29, -26, 3, 32, 33, 13, -32, 33, 7, -18, -6, -50, 13, -12, -11, -21, -59, 21, -56, -18, 52, -12, -22, 5, -50, 30, -31, -57, -30, -9, -5, 46, -24, -10, -82, 12, 34, 40, 56, -2, -58, -17, 32, 50, -26, 17, 39, 42, -33, 16, -28, -5, -35, 8, -10, 48, -11, -37, 
  32, 55, 35, -10, -49, 36, -7, -34, -5, -9, 4, 35, 33, -21, 9, -25, 24, -27, 57, 12, 53, 39, 51, 24, 36, 37, 41, -5, 48, -50, 32, -55, -8, -1, -47, -16, -50, 49, -38, 5, -29, -30, -52, -22, -50, 17, -20, -7, -30, 17, -53, -56, 57, -36, 29, 28, 8, 27, -6, -22, 37, -13, 49, -23, 3, -55, 50, 41, 36, -29, -24, -17, 10, -46, -18, -52, -42, -26, -32, 49, -28, -33, -45, -27, 49, 12, -3, 21, 33, 31, 0, -52, -52, -13, 44, -4, 53, 14, 26, -32, -40, -35, -26, 26, 6, 41, -14, 7, 15, -5, -26, 38, 10, 26, 45, 53, 19, -36, 48, -15, 40, 46, 3, -17, 30, -53, 10, 56, -52, 44, -52, 45, -58, -16, -40, -1, -42, 51, 14, 49, 49, -3, 40, -32, -47, 8, 24, -40, -52, -34, 51, 32, -31, -39, -28, 34, -57, -54, 32, -10, 34, 6, 9, -45, -15, -54, -49, 17, 13, 12, 49, -7, 9, 45, 49, -25, 45, -18, -58, 22, -50, -20, -41, -19, 0, 24, -43, -22, -52, 31, 29, 26, 1, 32, -46, 26, -7, -24, -52, 45, 41, 19, -19, -16, 17, -16, 7, -51, 
  -48, 26, -49, -4, -34, 34, -53, 0, -32, -58, -49, -40, -58, -15, -37, 45, -6, 34, 41, -37, -12, 37, 11, 54, 58, 39, 3, 17, -2, 26, -25, -16, -42, -2, 41, 18, 39, 44, -8, 8, 13, 24, -31, 14, -24, -58, 37, 24, 50, -45, 30, 55, -56, -55, -34, 11, 32, 6, -53, 18, -52, -32, -40, 44, 1, -14, -54, -16, -40, 24, -36, 38, 50, 1, -10, -44, 53, -16, -57, 40, 29, 56, -49, -33, -41, 44, -40, -31, 28, 11, 46, 22, -16, -7, 7, 53, -2, -54, -44, -26, 36, -45, -50, -21, 8, -3, -58, -26, 23, 21, 27, -31, -24, -26, 49, 38, 46, 32, 39, 28, 46, -56, -28, 50, -32, 26, 41, -19, -29, 23, -27, -33, -21, -16, -49, 26, 51, -1, 9, -57, 44, -40, 21, -3, 6, 21, 53, -5, -57, -6, -57, -53, -29, -45, 50, -49, -47, 28, -50, -11, -13, -57, 25, 23, 2, -58, -22, -29, -4, -35, 11, 41, 38, -19, -53, -35, 4, -42, 42, -11, -58, -2, 31, 43, 26, -40, 56, 40, -12, -2, 5, -31, -26, 54, 9, -49, -23, -19, -55, -10, 29, 15, -38, -16, 22, 35, 41, -43, 
  48, 62, 17, -50, -35, -22, 36, 12, -1, 22, -41, 23, 20, -14, 4, -62, 17, 26, 30, 18, -46, 31, -50, 49, 53, -7, -15, 46, 47, 31, -78, -38, -37, -4, 68, 62, -4, -35, -32, 34, -1, 28, -8, -49, -15, 44, 10, -49, 40, 32, -9, -26, -10, -38, 25, 54, -31, -22, 13, -9, 16, 21, 39, 42, 17, -55, -47, 10, 39, -8, 51, 13, -8, -21, 5, 55, 20, -35, 10, 60, 31, -44, 3, -41, -27, 34, -28, 8, -27, -37, -9, 52, -3, 0, -6, 4, -41, 9, -63, 19, 39, 25, 18, 13, 21, -73, 31, -48, 53, -9, -29, -12, 6, 15, -70, -6, -33, 42, -57, 4, -28, -50, -47, -59, 32, 14, -54, -2, 13, -67, 36, -91, -22, -46, 36, 20, -5, -49, 54, 37, -21, -41, -25, 2, -44, -49, -6, -23, 25, -22, 0, 32, 29, 51, -31, -32, -37, 78, 58, 5, 54, -49, 45, 20, -3, 7, 15, -34, -3, -1, 74, -2, -26, -47, 45, 49, 21, 4, 21, 55, 17, -50, 13, -36, -47, 49, -18, 29, 56, 6, -41, -57, 38, -58, 2, 15, -53, -32, -52, -6, 19, 45, 22, -23, -15, 33, 16, 32, 
  -7, 57, 31, -11, -37, -47, 62, -17, 48, -8, 55, 61, 44, 74, -41, -5, -5, 5, 61, 8, -8, -7, 59, 7, 24, 28, 48, 78, 51, 20, -21, -3, 12, -14, 27, -1, -27, 25, 28, 49, -14, 71, 41, -39, -24, -11, 21, 34, -42, 6, -34, 50, 10, -15, 36, 40, 45, -9, 6, -47, 44, 32, -1, -14, 42, 28, 25, -20, -2, -39, -39, 7, -28, -31, 51, 20, 29, 49, 17, 10, 69, 49, -65, -28, -51, -50, -38, 28, -5, 37, 29, -27, -87, -25, 20, 29, 28, 38, -10, -13, -5, -2, 45, 40, 48, -23, 21, 65, 15, -50, -15, 10, 22, 18, -55, -39, -58, 17, -2, 39, 64, 60, 3, -15, -7, -16, -30, -45, 57, 39, -45, -23, 53, -2, -29, 15, -39, 48, -26, 36, -1, 10, -6, 12, 10, -47, 4, -21, -36, -26, 44, -30, -4, 8, -6, 23, 14, 127, 71, -3, 70, -14, 6, 32, -48, 28, -20, -32, 40, 3, 45, 20, 55, -14, 52, 3, 57, 60, -9, 51, -18, 52, 17, 58, -81, 33, 29, 22, 54, 44, -47, -16, -4, -55, -21, 36, -12, 42, -46, -18, -8, -44, 53, -37, -41, 29, -33, -43, 
  -32, -61, -5, -24, 31, -56, -40, -62, -53, 22, -19, -59, 8, 25, -15, 37, 1, -25, 42, -22, 21, 26, -42, 30, 23, -24, -2, -31, 43, -21, -28, 8, -62, 46, 30, 30, 41, -44, -55, -42, -4, 4, -53, -34, -64, -29, 47, 27, -15, 52, 32, -57, -64, 12, -43, -62, -44, 12, -17, 19, -25, -48, -50, 32, 3, 8, 44, 19, -1, 34, -6, -33, 20, 31, 10, -63, -29, 38, -55, -55, 4, 19, 43, 31, 48, 38, -59, -39, -4, 29, -47, 48, 7, 5, -45, -57, 15, 0, 31, -19, -45, 28, 22, 12, -6, -53, -9, 40, 24, 3, -9, -25, -4, -34, -45, 3, -34, -23, 45, 26, 27, -12, 14, -37, 13, 17, -63, 26, -38, 43, -10, 36, 52, -10, 12, 47, 25, -9, 39, 52, 30, 6, 40, -21, -28, -17, -62, 34, -25, -64, 7, -48, -9, 12, -10, 50, -47, 26, -22, -34, 36, -24, -64, -29, -48, -62, -7, 51, -32, -38, 44, -31, -59, 14, 18, 28, -31, 5, -33, -63, -51, -20, -26, -5, 46, -49, -42, -55, -38, -49, -10, 50, 3, 29, -36, 48, -23, 22, -39, -35, 2, 22, -45, 43, -3, -58, 6, 50, 
  14, -58, -32, -3, 52, 56, -49, 54, -8, 14, 11, 15, 51, 15, -11, -41, -58, -9, -47, -21, -44, -46, -3, -19, -25, -58, -39, 50, -9, 4, 18, -56, -43, -56, -8, 14, 26, -4, 47, -18, 53, 28, 47, -42, 48, -28, -3, 33, 58, 35, 19, 27, -43, -28, 52, -23, 10, 40, 29, -10, 0, -20, -10, -45, 38, 44, 47, 45, 11, 55, -48, -11, 36, -11, 27, -42, -31, -27, 27, -34, -23, 26, -17, -20, 31, 9, 42, 49, -3, -57, 4, 12, -39, 31, -55, -42, -25, 54, 1, -29, 10, 50, 14, -43, -35, 25, 0, -6, -16, 24, 37, -52, -35, 17, -38, 31, 32, -33, 33, -50, -2, -22, -26, -19, 52, 10, -46, 45, 21, 49, -48, -45, 15, -2, -48, -53, 25, -21, -27, 47, 49, -8, 32, -56, -17, 39, 26, -31, 32, 53, -22, -43, -45, -45, -8, 51, -33, -9, 36, -25, -13, 39, 29, 12, 5, 4, 37, -50, -43, -20, 51, -22, 20, 16, -16, -46, 13, 42, -9, 2, 32, -42, -31, 10, 17, 19, -52, 3, 56, 36, -12, -57, 23, 32, -16, 9, -47, -11, 31, -58, -31, 3, 13, 28, 45, 18, 19, -30, 
  52, -49, -31, 11, 4, -35, -26, 20, 27, 19, 56, -57, -50, 56, -57, -22, -51, 7, 32, -46, 48, 56, -29, 42, -54, -34, -9, -48, 45, -16, 58, -31, -27, 35, -9, -38, -46, 13, 46, -53, -58, 47, -56, 37, -9, 35, -22, -37, -56, -25, -12, 25, 19, -10, -44, -38, 52, -14, 50, -33, 3, 24, -35, 52, 8, 52, 49, 36, -10, 30, 6, -35, 52, -24, 50, 27, -24, 14, -2, 5, 30, 6, -39, -27, 10, -46, 43, 5, -48, 11, -26, 18, -9, 32, -49, -2, 45, 45, 46, 58, -54, 53, -38, 42, -48, -21, 36, -51, -23, -34, -26, -2, 55, 30, -53, 35, 56, -49, 43, 47, -30, -8, -6, -35, -40, -45, -4, 54, 52, -39, -20, -35, -2, -2, 39, 30, 53, 26, -49, 46, -19, 22, -19, -29, 40, 39, 21, -36, 33, 41, -18, -41, 44, 37, 31, -32, -18, 33, -16, -49, 21, 34, 2, -6, -46, -29, 22, 15, 40, -29, 35, 28, -25, -31, -48, 30, 52, 34, 19, 34, -56, -39, -44, -1, 17, 17, 9, 19, 52, 19, -48, 4, -22, 49, -16, -15, -51, 10, 38, 41, 52, -58, 46, -27, -57, 33, -53, -21, 
  0, 49, -43, -54, -54, 16, -7, 9, 21, 19, -4, 22, -32, 27, 27, 45, 10, 26, 20, 34, -53, 48, -47, 25, 13, 0, -26, -21, -11, -32, 15, -20, -21, 30, -4, 12, 0, -53, 15, 51, 33, -28, 17, -41, 41, -36, -52, -14, -42, 40, 24, -5, 41, 49, 23, -33, 50, 25, -42, 48, 1, -36, 11, -25, 9, 24, 9, -34, 5, 37, -50, 47, 47, 50, 24, 41, -24, 13, 49, 21, -40, -34, 8, 54, 58, 44, 6, 30, 33, 58, -2, 57, 12, 37, 55, 41, -48, 28, 31, 26, 44, 50, 55, -18, 39, -36, 9, 23, 57, -33, 17, -49, -57, 10, 34, -36, -20, -51, -2, -6, -31, 11, -7, -21, 21, -14, -34, -27, -16, -43, -11, -17, 12, 49, -38, -23, -31, -17, 7, 8, -31, 17, -24, -4, 47, 10, 55, 7, -4, -45, 29, -20, -24, 45, 35, 23, -28, 39, -29, -47, -32, 55, -47, 33, 5, -17, -50, 38, 37, 5, -12, -28, -32, -38, 31, 56, -7, -55, -49, -14, 58, -24, -38, -32, -16, 12, -9, -22, 1, -57, -49, 34, 18, -49, 29, -46, -49, -47, 16, 23, 44, 49, -9, -18, 44, -3, 25, 42, 
  13, -22, -24, 4, 53, -3, -9, -31, 32, -40, -40, -7, 24, 38, -22, 17, -36, -22, 35, -9, -39, -24, 31, -15, 34, -9, 2, 44, -41, 53, 28, 11, 56, -24, -6, -20, 28, -39, -15, 16, -23, -7, 20, 52, 4, -35, 56, -42, 6, -12, 15, 4, -4, -42, -6, -43, 8, -3, 46, -32, -29, 59, -25, 12, -32, 34, -14, -7, 7, 68, -38, -2, -20, 59, 53, 40, -17, 26, -24, 16, 20, 59, -53, -8, 7, 50, 14, -24, 66, -2, 19, 76, 64, 11, 22, -11, 19, -4, 65, -13, 5, 7, 4, 6, 70, 54, 27, 66, 2, -20, 46, 27, 53, -41, -39, 32, -3, 71, -25, -47, 40, 5, -21, 8, 68, 25, 8, -37, 66, 65, -5, 34, -2, 23, -28, 10, 48, -31, 63, -42, 57, -5, 42, -16, -25, 14, 64, 45, 7, 18, -22, 0, 50, 35, 7, -17, 31, 58, -34, -4, -37, 28, -3, 53, 51, -24, 57, -45, -5, 15, 34, -10, 36, 54, 31, -7, 35, 51, -48, 60, 50, -17, -43, 24, 46, -20, -26, 42, -47, 36, 66, -44, -32, 62, 65, 42, 16, -31, -8, 28, -25, 42, -33, -13, 59, 32, -43, 1, 
  1, 41, 40, 48, 48, -10, -16, 55, 27, -1, -13, 63, -14, 48, -61, -34, -30, 26, 60, -26, 37, -20, -38, 62, -26, -40, -24, 14, -12, -25, 3, -36, 9, 22, 13, 64, 63, -24, 48, -37, -101, 16, 56, -33, 24, -31, 13, 62, -37, 36, -20, -25, 44, 13, 24, -30, 70, -49, -12, -27, 17, -44, 29, 55, -12, 19, -39, 23, 21, -23, 48, -18, 40, 56, 29, 17, -43, -39, 58, -49, -52, -50, -54, 19, 39, 66, -9, 29, 27, 41, 14, 91, -63, -38, 59, 62, 45, -1, 71, -33, 70, 44, 25, -16, 0, -80, -60, 68, 38, -36, -31, -6, 66, 24, -18, 39, 60, 90, -52, -24, -18, 82, 34, 70, 20, 44, 47, 69, 75, 69, 19, 3, -13, 58, 34, -9, 58, 38, 16, -10, -54, -50, -50, 32, 37, -1, 24, 34, 52, 1, 32, 52, -52, -37, 21, -12, -23, 35, 50, -17, -20, -49, -53, 1, 51, 46, -47, -23, 52, 5, -56, -31, 50, 59, 48, 50, 16, 13, -16, 48, 62, 53, 43, -2, -71, 35, 64, -11, 14, -41, 41, 49, 3, 57, 52, -56, -23, 46, 33, -18, 2, -25, 11, -35, 18, -23, 24, -14, 
  -49, -15, 31, -56, 28, 5, -38, -5, -2, -20, -53, -22, -49, -41, -43, -30, 4, -34, -32, 22, -29, 48, -32, 46, -25, -50, -2, -16, -52, -40, 27, -25, -37, -52, 57, 46, 16, -39, -45, -19, -42, 12, -35, 30, 2, -9, 58, 13, -46, -53, 3, -49, 26, -33, 37, -41, -38, -36, -16, 41, -18, -30, -38, 45, 29, -30, 50, -47, 3, 51, 36, 32, 44, -26, -55, 17, 52, 10, -17, 20, 16, 24, 50, -2, 28, 10, 49, 6, -3, -46, -55, 46, 37, -19, -42, -42, 32, 13, 55, -35, -58, 57, 14, 6, -29, 1, -30, -42, 3, 32, -39, 7, -57, -31, -32, -43, 26, 24, -50, -51, 50, -32, -15, 10, 16, 55, -12, -24, 3, 4, -51, -26, 2, -3, -9, -31, 15, 56, -24, 17, 41, -18, -8, -24, 48, 43, 14, 18, -10, -14, -3, 22, 47, 26, -1, -29, 27, -23, 55, -9, 16, -25, 21, -46, -18, -50, -24, 58, -5, 35, 47, -43, 55, 42, -6, 29, -36, -28, 41, 36, 25, -23, -52, 52, 45, -43, -53, -34, -8, 6, -2, 7, -17, -24, 11, -22, -23, -25, 34, -44, 37, -45, -20, 23, -10, -28, -36, 12, 
  -2, 44, 3, -28, -10, -19, 17, -8, 42, 39, -47, 46, 40, -1, -1, -24, -2, -48, -31, 16, -22, -53, 45, -45, -4, 2, -37, -24, 20, 46, -40, 9, 49, -36, 5, 20, -53, 13, 4, -7, -38, -40, 15, 32, 0, -47, -54, 16, -6, 2, 15, 27, -49, 20, 27, -30, 31, -48, -39, 48, -45, 39, -42, 20, -44, -6, -9, -39, -42, -34, -55, 38, -17, -8, -13, 20, -48, -57, -51, -26, 45, -4, -2, -49, -12, 21, 51, -6, 17, 1, -54, 9, -39, -13, 17, -48, -38, -41, 58, -34, -18, 44, 39, -44, -10, 36, -55, -41, -4, 34, 58, 43, -49, -36, 26, 7, -5, -33, -26, -4, 57, 8, 25, -29, 17, 38, -52, 0, -30, 0, -41, 1, 46, 32, 7, 57, 27, 45, -31, -23, 22, -37, 20, 15, 1, 45, -41, 45, -12, 22, -57, 29, -12, -21, 3, -53, -45, -11, -2, 31, -46, -56, 44, -18, 16, -47, 37, 33, 47, -37, -22, 36, 20, -15, 9, 32, -45, 2, -37, -19, 13, -39, -19, -7, -22, 19, -42, -15, -20, 49, -20, -13, 57, 27, 5, 35, -45, -42, 50, -46, 22, -57, 7, 34, 29, -11, -34, 46, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,208 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0027849867474287748, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<1, float> quant7_scale = { 1, { 11.61458683013916, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<1, float> quant8_scale = { 1, { 11.142599105834961, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,4 } };
const TfArray<1, float> quant9_scale = { 1, { 4.214388370513916, } };
const TfArray<1, int> quant9_zero = { 1, { 69 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 208, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 4160, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 208), (TfLiteIntArray*)&g0::tensor_dimension7, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 4, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 4, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_991408_9_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_991408_9_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_991408_9_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_991408_9_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_991408_9_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
